import test from 'node:test';
import assert from 'node:assert/strict';
import { initialCommercialState, applyCommercial, commercialView, quoteTotals, tenderRoute, commercialApplication, commercialAccess } from '../server/commercial.ts';
const NOW=Date.parse('2026-09-16T18:00:00Z'), future='2026-10-16T00:00:00Z', past='2026-09-15T00:00:00Z', actor='operator-1';
function flow({testRecord=false}={}) {
 const state=initialCommercialState();
 const run=(type,payload)=>applyCommercial(state,{type,payload},actor,NOW);
 const account=run('account.create',{name:'Example installer',domain:'example.org',kind:'security_partner',sourceRef:'SOURCE-001',testRecord});
 run('account.permission',{id:account.id,permission:'consented',evidenceRef:'CONSENT-001'});
 const deal=run('deal.create',{accountId:account.id,title:'First three sites',lane:'partner',nextAction:'Book a setup call',dueAt:past});
 const qualify=()=>run('deal.qualify',{id:deal.id,buyerRole:'Owner',problem:'Manual event handling',evidenceRef:'DISCOVERY-001'});
 const quote=()=>run('quote.create',{id:deal.id,lines:[{label:'Software',quantity:3,unitMinor:45000,cadence:'monthly'},{label:'Commissioning',quantity:1,unitMinor:50000,cadence:'once'}],expiresAt:future,directCostMinor:40000,channelCostMinor:0,scope:'Three supported sites; eight sources each.'});
 const contract=()=>run('contract.record',{id:deal.id,quoteId:deal.quotes.at(-1).id,evidenceRef:'CONTRACT-001'});
 const receipt=(category='service',reference='SETTLEMENT-001')=>run('receipt.record',{id:deal.id,reference,grossMinor:155250,taxMinor:20250,category,paidAt:past,evidenceRef:'BANK-001'});
 const activate=(siteRefs=['site-1','site-2','site-3'])=>run('activation.record',{id:deal.id,siteRefs,startedAt:past,renewalAt:future,acceptanceRef:'ACCEPT-001',commissioningRef:'INSTALL-001'});
 return {state,run,account,deal,qualify,quote,contract,receipt,activate};
}
const throws=(fn,status)=>assert.throws(fn,e=>e.status===status);
test('empty workspace contains no fabricated business results',()=>{
 const v=commercialView(initialCommercialState(),NOW);assert.equal(v.metrics.activatedMrrMinor,0);assert.equal(v.metrics.recordedCashMinor,0);assert.equal(v.deals.length,0);assert.equal(v.integrations.bankSync,false);
});
test('whole commercial journey preserves pipeline/cash/MRR distinctions',()=>{
 const f=flow();f.qualify();f.quote();assert.equal(commercialView(f.state,NOW).metrics.qualifiedPipelineMrrMinor,135000);assert.equal(commercialView(f.state,NOW).metrics.activatedMrrMinor,0);
 f.contract();f.receipt();assert.equal(commercialView(f.state,NOW).metrics.activatedMrrMinor,0);f.activate();const m=commercialView(f.state,NOW).metrics;
 assert.equal(m.activatedMrrMinor,135000);assert.equal(m.recordedCashMinor,155250);assert.equal(m.recordedServiceCashMinor,135000);assert.equal(m.activatedSites,3);assert.equal(m.productivePartners,1);assert.equal(m.qualifiedPipelineMrrMinor,0);
});
test('duplicate account names/domains are rejected',()=>{const f=flow();throws(()=>f.run('account.create',{name:'Different name',domain:'https://www.example.org/path',kind:'business',sourceRef:'SOURCE-002'}),409);});
test('research-only and opt-out accounts cannot progress to a sales quote',()=>{const f=flow();f.run('account.permission',{id:f.account.id,permission:'do_not_contact',evidenceRef:'OPT-OUT-001'});throws(f.qualify,409);assert.equal(commercialView(f.state,NOW).actions[0].kind,'contact_hold');});
test('qualification needs evidence and a buyer role',()=>{const f=flow();throws(()=>f.run('deal.qualify',{id:f.deal.id,problem:'Delays',buyerRole:'',evidenceRef:'DISCOVERY-1'}),400);});
test('quotes cannot skip buyer qualification',()=>{const f=flow();throws(f.quote,409);});
test('quotes are versioned and earlier prices remain unchanged',()=>{const f=flow();f.qualify();const one=f.quote();const snapshot=JSON.stringify(one);f.quote();assert.equal(f.deal.quotes.length,2);assert.equal(JSON.stringify(f.deal.quotes[0]),snapshot);throws(()=>f.run('contract.record',{id:f.deal.id,quoteId:one.id,evidenceRef:'CONTRACT-1'}),409);});
test('quotes exclude setup fees from MRR and normalise annual pricing',()=>{const q=quoteTotals([{label:'Annual software',quantity:1,unitMinor:120000,cadence:'annual'},{label:'Setup',quantity:1,unitMinor:50000,cadence:'once'}]);assert.equal(q.monthlyMinor,10000);assert.equal(q.onceMinor,50000);});
test('money calculations reject fractional cents, negatives and unsafe magnitudes',()=>{for(const unitMinor of [-1,1.2,Infinity,Number.MAX_SAFE_INTEGER])throws(()=>quoteTotals([{label:'X',quantity:1,unitMinor,cadence:'monthly'}]),400);throws(()=>quoteTotals([{label:'X',quantity:0,unitMinor:1,cadence:'once'}]),400);});
test('negative contribution requires a referenced exception',()=>{const f=flow();f.qualify();throws(()=>f.run('quote.create',{id:f.deal.id,lines:[{label:'Software',quantity:1,unitMinor:100,cadence:'monthly'}],expiresAt:future,directCostMinor:200,channelCostMinor:0,scope:'One site'}),400);});
test('an expired quote cannot be accepted',()=>{const f=flow();f.qualify();f.quote();throws(()=>applyCommercial(f.state,{type:'contract.record',payload:{id:f.deal.id,quoteId:f.deal.quotes[0].id,evidenceRef:'SIGNED-1'}},actor,Date.parse('2026-11-01T00:00:00Z')),409);});
test('deposits, hardware and pass-through money do not activate MRR',()=>{for(const category of ['deposit','hardware','pass_through']){const f=flow();f.qualify();f.quote();f.contract();f.receipt(category);throws(()=>f.activate(),409);assert.equal(commercialView(f.state,NOW).metrics.activatedMrrMinor,0);}});
test('duplicate receipt references cannot inflate collections',()=>{const f=flow();f.qualify();f.quote();f.contract();f.receipt();throws(()=>f.receipt(),409);assert.equal(f.deal.receipts.length,1);});
test('receipts cannot have future settlement dates or more tax than gross',()=>{const f=flow();f.qualify();f.quote();f.contract();for(const overrides of [{paidAt:future},{taxMinor:99999}])throws(()=>f.run('receipt.record',{id:f.deal.id,reference:'R1',grossMinor:1000,taxMinor:0,category:'service',paidAt:past,evidenceRef:'BANK-1',...overrides}),400);});
test('activation requires acceptance and commissioning evidence',()=>{const f=flow();f.qualify();f.quote();f.contract();f.receipt();throws(()=>f.run('activation.record',{id:f.deal.id,siteRefs:['s1'],startedAt:past,renewalAt:future,acceptanceRef:'',commissioningRef:'INSTALL-1'}),400);});
test('active site attribution cannot be duplicated across contracts',()=>{const f=flow();f.qualify();f.quote();f.contract();f.receipt();f.activate();const d=f.run('deal.create',{accountId:f.account.id,title:'Second contract',lane:'operations',nextAction:'Research',dueAt:future});d.stage='contracted';d.contract={quoteId:'q'};d.quotes=[{id:'q',monthlyMinor:100}];d.receipts=[{kind:'receipt',category:'service',netMinor:100}];throws(()=>f.run('activation.record',{id:d.id,siteRefs:['site-1'],startedAt:past,renewalAt:future,acceptanceRef:'ACCEPT-2',commissioningRef:'INSTALL-2'}),409);});
test('test accounts remain excluded from all revenue and productive-partner metrics',()=>{const f=flow({testRecord:true});f.qualify();f.quote();f.contract();f.receipt();f.activate();const m=commercialView(f.state,NOW).metrics;assert.equal(m.activatedMrrMinor,0);assert.equal(m.recordedCashMinor,0);assert.equal(m.productivePartners,0);});
test('refunds are additive records, reverse totals, and cannot exceed the receipt',()=>{const f=flow();f.qualify();f.quote();f.contract();const r=f.receipt();f.activate();f.run('receipt.refund',{id:f.deal.id,receiptId:r.id,reference:'REFUND-001',grossMinor:155250,taxMinor:20250,paidAt:past,evidenceRef:'REFUND-BANK-001'});assert.equal(f.deal.receipts.length,2);assert.equal(commercialView(f.state,NOW).metrics.recordedCashMinor,0);assert.equal(commercialView(f.state,NOW).metrics.activatedMrrMinor,0);assert.ok(commercialView(f.state,NOW).actions.some(a=>a.kind==='reconciliation'));throws(()=>f.run('receipt.refund',{id:f.deal.id,receiptId:r.id,reference:'REFUND-002',grossMinor:1,taxMinor:0,paidAt:past,evidenceRef:'REFUND-BANK-002'}),400);});
test('ending a service removes it from MRR without deleting its history',()=>{const f=flow();f.qualify();f.quote();f.contract();f.receipt();f.activate();f.run('service.end',{id:f.deal.id,endedAt:past,reason:'Customer cancelled',evidenceRef:'CANCEL-001'});assert.equal(commercialView(f.state,NOW).metrics.activatedMrrMinor,0);assert.equal(f.deal.receipts.length,1);});
test('overdue renewals are surfaced and excluded until reconfirmed',()=>{const f=flow();f.qualify();f.quote();f.contract();f.receipt();f.activate();const later=Date.parse('2026-10-17T00:00:00Z'),v=commercialView(f.state,later);assert.equal(v.metrics.activatedMrrMinor,0);assert.ok(v.actions.some(a=>a.kind==='renewal'));});
test('no unknown procurement requirement is treated as eligible',()=>{const t={closesAt:future,briefingAt:null,gates:[],partnerRequired:false};assert.equal(tenderRoute(t,NOW),'check_requirements');t.gates=[{status:'pass'}];assert.equal(tenderRoute(t,NOW),'review_before_bid');t.gates=[{status:'fail'}];assert.equal(tenderRoute(t,NOW),'not_eligible');});
test('missed compulsory briefing and expired deadline override other tender checks',()=>{const t={closesAt:future,briefingAt:past,briefingAttended:false,gates:[{status:'pass'}]};assert.equal(tenderRoute(t,NOW),'missed_briefing');assert.equal(tenderRoute({...t,closesAt:past},NOW),'closed');});
test('tender partner dependency is explicit',()=>{const t={closesAt:future,gates:[{status:'pass'}],partnerRequired:true,partnerRef:null};assert.equal(tenderRoute(t,NOW),'partner_needed');});
test('secret-bearing URLs and impossible dates are rejected',()=>{const f=flow();throws(()=>f.run('account.permission',{id:f.account.id,permission:'consented',evidenceRef:'https://example.org/?token=secret'}),400);throws(()=>f.run('deal.next_action',{id:f.deal.id,nextAction:'Review',dueAt:'2026-02-30T00:00:00Z'}),400);});
class MemoryStorage { data=new Map(); async read(k){return structuredClone(this.data.get(k)||null);} async write(k,data,etag){const old=this.data.get(k);if((old?.etag??null)!==etag)return false;this.data.set(k,{data:structuredClone(data),etag:String(Number(old?.etag||0)+1)});return true;} }
const origin='https://edgebox.example';
const req=(path='/api/v1/commercial',body,extra={})=>new Request(origin+path,{method:body===undefined?'GET':'POST',headers:{Origin:origin,'Content-Type':'application/json','Idempotency-Key':'command-001',...extra},...(body===undefined?{}:{body:JSON.stringify(body)})});
const createCommand={revision:0,type:'account.create',payload:{name:'Example company',kind:'business',sourceRef:'SOURCE-001'}};
test('HTTP authorization denies access before touching commercial storage',async()=>{const storage={read(){throw Error('MUST NOT READ');},write(){throw Error('MUST NOT WRITE');}};const app=commercialApplication({storage,origin,authorize:async()=>{throw Object.assign(new Error('denied'),{});}});assert.equal((await app(req())).status,503);});
test('HTTP command retries are idempotent and changed payloads conflict',async()=>{const storage=new MemoryStorage(),app=commercialApplication({storage,origin,authorize:async()=>actor,now:()=>NOW});assert.equal((await app(req('/api/v1/commercial/commands',createCommand))).status,201);const repeated=await app(req('/api/v1/commercial/commands',createCommand));assert.equal((await repeated.json()).replayed,true);const changed=await app(req('/api/v1/commercial/commands',{...createCommand,payload:{...createCommand.payload,name:'Other'}}));assert.equal(changed.status,409);assert.equal((await (await app(req())).json()).accounts.length,1);});
test('two concurrent writes cannot overwrite one another',async()=>{const storage=new MemoryStorage(),app=commercialApplication({storage,origin,authorize:async()=>actor,now:()=>NOW});const result=await Promise.all([app(req('/api/v1/commercial/commands',createCommand)),app(req('/api/v1/commercial/commands',{...createCommand,payload:{...createCommand.payload,name:'Other'}},{'Idempotency-Key':'command-002'}))]);assert.deepEqual(result.map(r=>r.status).sort(),[201,409]);});
test('HTTP export omits request replay storage and sends no-store',async()=>{const app=commercialApplication({storage:new MemoryStorage(),origin,authorize:async()=>actor,now:()=>NOW});const r=await app(req('/api/v1/commercial/export'));assert.equal(r.headers.get('cache-control'),'no-store');assert.equal((await r.json()).operations,undefined);});
test('HTTP rejects cross-origin, missing content type, oversized body and unknown routes',async()=>{const app=commercialApplication({storage:new MemoryStorage(),origin,authorize:async()=>actor,now:()=>NOW});assert.equal((await app(req('/api/v1/commercial/commands',createCommand,{Origin:'https://evil.example'}))).status,403);assert.equal((await app(req('/api/v1/commercial/commands',createCommand,{'Content-Type':'text/plain'}))).status,415);assert.equal((await app(req('/api/v1/commercial/commands',{padding:'x'.repeat(33000)}))).status,413);assert.equal((await app(req('/api/v1/commercial/unknown',{}))).status,404);});
test('storage failures are redacted',async()=>{const app=commercialApplication({storage:{read:async()=>{throw Error('secret value');}},origin,authorize:async()=>actor});const r=await app(req());assert.equal(r.status,503);assert.equal((await r.text()).includes('secret value'),false);});
function baseMock({status=200}={}) {return async r=>r.url.endsWith('/admin/session')?Response.json(status===200?{admin:true,operator:{id:'operator'},csrf:'csrf-proof'}:{error:'denied'},{status}):Response.json({error:'not found'},{status:404});}
test('auth adapter denies ordinary customers, partners and signed-out users',async()=>{for(const status of [403,401,503])await assert.rejects(()=>commercialAccess(baseMock({status}))(req(),'ip'),e=>e.status===status);});
test('auth adapter requires session CSRF even for internal operators',async()=>{const auth=commercialAccess(baseMock());await assert.rejects(()=>auth(req('/api/v1/commercial/commands',{}),'ip'),e=>e.status===403);assert.equal(await auth(req('/api/v1/commercial/commands',{}, {'X-CSRF-Token':'csrf-proof'}),'ip'),'operator');});
test('the R100M goal is a target, not counted as actual or pipeline revenue',()=>{const m=commercialView(initialCommercialState(),NOW).metrics;assert.equal(m.targetMrrMinor,10000000000);assert.equal(m.qualifiedPipelineMrrMinor,0);assert.equal(m.nextGateMinor,10000000);});
