import test from 'node:test';
import assert from 'node:assert/strict';
import { application, digest } from '../server/app.ts';
class MemoryStorage {
  values=new Map(); revision=0;
  async read(key){const v=this.values.get(key);return v?structuredClone(v):null;}
  async write(key,data,etag){const old=this.values.get(key);if((old?.etag??null)!==etag)return false;this.values.set(key,{data:structuredClone(data),etag:String(++this.revision)});return true;}
}
function fixture(storage=new MemoryStorage(),sub='google-sub-1',email='person@gmail.com',internalSubs=[]){
  let time=Date.parse('2026-09-15T12:00:00Z'), google={};
  const settings={origin:'https://edgebox.africa',googleClientId:'test.apps.googleusercontent.com',internalSubs};
  const app=application({storage,settings,now:()=>time,verifyGoogle:async token=>{if(token!=='verified-fixture')throw Error();return google;}});
  let cookie='',csrf='',org='';
  const call=async(path,method='GET',body,extra={})=>{
    const headers={Origin:settings.origin,Cookie:cookie,'Content-Type':'application/json','X-CSRF-Token':csrf,'Idempotency-Key':crypto.randomUUID(),...(org?{'X-Edgebox-Org':org}:{}),...extra};
    const response=await app(new Request(settings.origin+'/api/v1'+path,{method,headers,...(body===undefined?{}:{body:JSON.stringify(body)})}),'127.0.0.1');
    return {status:response.status,data:await response.json(),response};
  };
  const signin=async()=>{
    const challenge=await call('/auth/challenge','POST',{});
    const loginCookie=challenge.response.headers.get('set-cookie').split(';')[0];
    google={iss:'https://accounts.google.com',aud:settings.googleClientId,exp:time/1000+3600,sub,email,email_verified:true,nonce:challenge.data.nonce};
    const r=await call('/auth/google','POST',{credential:'verified-fixture'},{Cookie:loginCookie});
    if(r.status===200){cookie=r.response.headers.get('set-cookie').split(';')[0];csrf=r.data.csrf;}
    return r;
  };
  const onboard=async(type='business',name='Test org',extra={})=>{const r=await call('/onboarding','POST',{type,name},extra);if(r.status===201)org=r.data.org_id;return r;};
  const login=async(type='business',name='Test org')=>{await signin();await onboard(type,name);};
  return {storage,settings,call,signin,onboard,login,app,sub,email,setTime:v=>time=v,setGoogle:v=>google=v,getTime:()=>time,setOrg:v=>org=v,getOrg:()=>org,setCsrf:v=>csrf=v};
}
async function source(f){await f.login();const site=await f.call('/sites','POST',{name:'Test site',kind:'business'});const s=await f.call('/sources','POST',{name:'Gateway',site_id:site.data.id,brand:'Webhook'});const key=await f.call('/api-keys','POST',{source_id:s.data.id});return {site:site.data,source:s.data,key:key.data};}
const event=(id='evt_1')=>({event_id:id,event_type:'connection.test',occurred_at:'2026-09-15T12:00:00Z'});

test('public health is real capability metadata and signup is open; anonymous dashboard rejected',async()=>{const f=fixture();assert.equal((await f.call('/health')).status,200);assert.equal((await f.call('/auth/config')).data.account_signup,true);assert.equal((await f.call('/dashboard')).status,401);});
test('any verified Google account signs in, is prompted to onboard, then creates its own org',async()=>{const f=fixture();const r=await f.signin();assert.equal(r.status,200);assert.match(r.response.headers.get('set-cookie'),/Secure; HttpOnly; SameSite=Lax/);assert.equal(r.data.onboarding,true);assert.deepEqual(r.data.orgs,[]);const o=await f.onboard('home','My house');assert.equal(o.status,201);assert.equal(o.data.type,'home');assert.equal((await f.call('/orgs')).data.orgs.length,1);assert.equal((await f.call('/auth/session')).data.onboarding,false);});
test('retired owner code endpoint is gone',async()=>{const f=fixture();await f.login();assert.equal((await f.call('/auth/owner','POST',{code:'anything'})).status,404);});
test('forged session cookie and expired session are rejected',async()=>{const f=fixture();await f.login();assert.equal((await f.call('/dashboard','GET',undefined,{Cookie:'__Host-eb-session=forged'})).status,401);const g=fixture();await g.login();g.setTime(g.getTime()+43200001);assert.equal((await g.call('/dashboard')).status,401);});
test('cross origin, missing origin and CSRF attacks fail',async()=>{const f=fixture();await f.login();for(const headers of [{Origin:'https://evil.test'},{Origin:''},{'X-CSRF-Token':'wrong'}])assert.equal((await f.call('/sites','POST',{name:'Bad',kind:'home'},headers)).status,403);});
test('logout revokes server-side session',async()=>{const f=fixture();await f.login();assert.equal((await f.call('/auth/logout','POST',{})).status,200);assert.equal((await f.call('/dashboard')).status,401);});
test('a resource request without an org header is rejected',async()=>{const f=fixture();await f.signin();assert.equal((await f.call('/dashboard')).status,400);assert.equal((await f.call('/sites','POST',{name:'X',kind:'home'})).status,400);});
test('site creates replay safely and conflicting idempotency payload fails',async()=>{const f=fixture();await f.login();const headers={'Idempotency-Key':'stable'},data={name:'Depot',kind:'business'};const one=await f.call('/sites','POST',data,headers),two=await f.call('/sites','POST',data,headers);assert.equal(one.data.id,two.data.id);assert.equal((await f.call('/sites','POST',{...data,name:'Other'},headers)).status,409);assert.equal((await f.call('/dashboard')).data.sites.length,1);});
test('concurrent writes retain both updates with compare-and-swap',async()=>{const f=fixture();await f.login();const result=await Promise.all(['A','B','C'].map(name=>f.call('/sites','POST',{name,kind:'home'})));assert.ok(result.every(r=>r.status===201));assert.equal((await f.call('/dashboard')).data.sites.length,3);});
test('onboarding is idempotent: repeated submit and same type+name never create a second org',async()=>{const f=fixture();await f.signin();const key={'Idempotency-Key':'onb-1'};const a=await f.onboard('home','Home',key),b=await f.onboard('home','Home',key);assert.equal(a.data.org_id,b.data.org_id);const c=await f.onboard('home','Home');assert.equal(c.data.org_id,a.data.org_id);assert.equal((await f.call('/orgs')).data.orgs.length,1);});
test('concurrent first-login for one Google subject converges to a single identity',async()=>{const store=new MemoryStorage();const a=fixture(store),b=fixture(store);await Promise.all([a.signin(),b.signin()]);const ids=[...store.values.keys()].filter(k=>k.startsWith('identity/'));assert.equal(ids.length,1);});
test('two identities get isolated orgs; a forged org header and a foreign site id are denied',async()=>{const store=new MemoryStorage();const a=fixture(store,'sub-a','a@gmail.com'),b=fixture(store,'sub-b','b@gmail.com');const x=await source(a);await b.login();assert.equal((await b.call('/dashboard','GET',undefined,{'X-Edgebox-Org':a.getOrg()})).status,403);assert.equal((await b.call('/sources','POST',{name:'Bad',site_id:x.site.id},{'X-Edgebox-Org':a.getOrg()})).status,403);assert.equal((await b.call('/sources','POST',{name:'Bad',site_id:x.site.id})).status,404);assert.equal((await b.call('/dashboard')).data.sites.length,0);});
test('an org that lists neither a member nor a delegation for the caller denies access',async()=>{const store=new MemoryStorage();const f=fixture(store);await f.login();const ghost='dead'.repeat(8);await store.write(`orgs/${ghost}`,{orgId:ghost,type:'business',name:'Ghost',createdAt:'x',members:[],delegations:[],sites:[],sources:[],keys:[],events:[],requests:[],audit:[],operations:[]},null);assert.equal((await f.call('/dashboard','GET',undefined,{'X-Edgebox-Org':ghost})).status,403);assert.equal((await f.call('/sites','POST',{name:'X',kind:'home'},{'X-Edgebox-Org':ghost})).status,403);});
test('new source is awaiting events and API key is excluded from dashboard and export',async()=>{const f=fixture(),x=await source(f);const data=(await f.call('/dashboard')).data;assert.equal(data.sources[0].status,'awaiting_events');assert.ok(!JSON.stringify(data).includes(x.key.api_key));assert.ok(!JSON.stringify((await f.call('/export')).data).includes(digest(x.key.api_key)));});
test('external events persist once, replay safely and conflict on changed payload',async()=>{const f=fixture(),x=await source(f),h={Authorization:`Bearer ${x.key.api_key}`};const a=await f.call('/events','POST',event(),h);assert.equal(a.status,200);assert.equal(a.data.accepted,true);assert.equal((await f.call('/events','POST',event(),h)).data.duplicate,true);assert.equal((await f.call('/events','POST',{...event(),event_type:'camera.offline'},h)).status,409);const d=(await f.call('/dashboard')).data;assert.equal(d.events.length,1);assert.equal(d.sources[0].status,'receiving_events');assert.equal(d.usage.amount_due_minor,0);});
test('revoked keys cannot write and event body cannot change credential scope',async()=>{const f=fixture(),x=await source(f),h={Authorization:`Bearer ${x.key.api_key}`};assert.equal((await f.call('/events','POST',{...event(),source_id:'spoofed'},h)).status,400);assert.equal((await f.call(`/api-keys/${x.key.id}/revoke`,'POST',{})).status,200);assert.equal((await f.call('/events','POST',event(),h)).status,401);});
test('event acknowledgement is persistent and tenant scoped',async()=>{const f=fixture(),x=await source(f);await f.call('/events','POST',event(),{Authorization:`Bearer ${x.key.api_key}`});assert.equal((await f.call('/events/evt_1/acknowledge','POST',{source_id:x.source.id})).status,200);assert.ok((await f.call('/dashboard')).data.events[0].acknowledgedAt);});
test('malformed timestamps, raw imagery and oversized requests rejected',async()=>{const f=fixture(),x=await source(f),h={Authorization:`Bearer ${x.key.api_key}`};for(const v of [{...event(),occurred_at:'2026-02-30T12:00:00Z'},{...event(),image:'sensitive'},{...event(),duration_seconds:-1}])assert.equal((await f.call('/events','POST',v,h)).status,400);assert.equal((await f.call('/events','POST',{...event(),blob:'x'.repeat(33000)},h)).status,413);});
test('service requests save intent but never create a payment or subscription',async()=>{const f=fixture(),x=await source(f);const r=await f.call('/service-requests','POST',{site_id:x.site.id,service:'camera-connection'});assert.equal(r.status,201);const d=(await f.call('/dashboard')).data;assert.equal(d.requests.length,1);assert.equal(d.usage.plan,'No paid subscription');assert.equal(d.capabilities.payments,false);});
test('Google uses one-time nonce, expected audience, verified email and validated credential',async()=>{const f=fixture();const r=await f.signin();assert.equal(r.status,200);const challenge=await f.call('/auth/challenge','POST',{}),c=challenge.response.headers.get('set-cookie').split(';')[0];f.setGoogle({iss:'https://accounts.google.com',aud:f.settings.googleClientId,exp:f.getTime()/1000+3600,sub:'google-sub-1',email:'person@gmail.com',email_verified:true,nonce:challenge.data.nonce});const first=await f.call('/auth/google','POST',{credential:'verified-fixture'},{Cookie:c});assert.equal(first.status,200);assert.equal((await f.call('/auth/google','POST',{credential:'verified-fixture'},{Cookie:c})).status,401);});
test('Google rejects unverified tokens, wrong audience, nonce and expired claims',async()=>{for(const patch of [{aud:'other'},{nonce:'other'},{email_verified:false},{exp:1},{iss:'https://evil.test'}]){const f=fixture(),challenge=await f.call('/auth/challenge','POST',{}),c=challenge.response.headers.get('set-cookie').split(';')[0];f.setGoogle({iss:'https://accounts.google.com',aud:f.settings.googleClientId,exp:f.getTime()/1000+3600,sub:'sub',email:'person@gmail.com',email_verified:true,nonce:challenge.data.nonce,...patch});assert.equal((await f.call('/auth/google','POST',{credential:'verified-fixture'},{Cookie:c})).status,401);assert.equal((await f.call('/auth/google','POST',{credential:'forged'},{Cookie:c})).status,401);}});
test('an undefined endpoint is denied, not silently accepted',async()=>{const f=fixture();await f.login();assert.equal((await f.call('/sites/wipe','POST',{})).status,404);});
test('storage failure never produces a false successful save',async()=>{const f=fixture();await f.login();f.storage.write=async()=>{throw Error('backend offline');};const r=await f.call('/sites','POST',{name:'Depot',kind:'business'});assert.equal(r.status,503);assert.ok(!JSON.stringify(r.data).includes('backend offline'));});

// ---- Phase 2: roles, invitations, delegation, admin ----
test('invited member acts within its role but cannot manage members',async()=>{const store=new MemoryStorage();const a=fixture(store,'sub-a','a@gmail.com');await a.login('business','A Org');const aOrg=a.getOrg();const inv=await a.call('/members','POST',{email:'b@gmail.com',role:'member'});assert.equal(inv.status,201);assert.equal(inv.data.pending,true);const b=fixture(store,'sub-b','b@gmail.com');const s=await b.signin();assert.ok(s.data.orgs.some(o=>o.org_id===aOrg && o.role==='member'));assert.equal((await b.call('/sites','POST',{name:'Depot',kind:'business'},{'X-Edgebox-Org':aOrg})).status,201);assert.equal((await b.call('/members','POST',{email:'c@gmail.com',role:'member'},{'X-Edgebox-Org':aOrg})).status,403);assert.equal((await b.call('/members','GET',undefined,{'X-Edgebox-Org':aOrg})).status,403);});
test('viewer can read but not write',async()=>{const store=new MemoryStorage();const a=fixture(store,'sub-a','a@gmail.com');await a.login('business','A');const aOrg=a.getOrg();await a.call('/members','POST',{email:'v@gmail.com',role:'viewer'});const v=fixture(store,'sub-v','v@gmail.com');await v.signin();assert.equal((await v.call('/dashboard','GET',undefined,{'X-Edgebox-Org':aOrg})).status,200);assert.equal((await v.call('/sites','POST',{name:'X',kind:'home'},{'X-Edgebox-Org':aOrg})).status,403);});
test('a pending invite grants nothing until the invited email signs in and claims it',async()=>{const store=new MemoryStorage();const a=fixture(store,'sub-a','a@gmail.com');await a.login('business','A');const aOrg=a.getOrg();await a.call('/members','POST',{email:'b@gmail.com',role:'member'});const before=(await a.call('/members','GET',undefined,{'X-Edgebox-Org':aOrg})).data.members.find(m=>m.email==='b@gmail.com');assert.equal(before.pending,true);const b=fixture(store,'sub-b','b@gmail.com');await b.signin();const after=(await a.call('/members','GET',undefined,{'X-Edgebox-Org':aOrg})).data.members.find(m=>m.email==='b@gmail.com');assert.equal(after.pending,false);});
test('member removal cuts access immediately',async()=>{const store=new MemoryStorage();const a=fixture(store,'sub-a','a@gmail.com');await a.login('business','A');const aOrg=a.getOrg();await a.call('/members','POST',{email:'b@gmail.com',role:'member'});const b=fixture(store,'sub-b','b@gmail.com');await b.signin();assert.equal((await b.call('/dashboard','GET',undefined,{'X-Edgebox-Org':aOrg})).status,200);assert.equal((await a.call('/members/b@gmail.com/remove','POST',{},{'X-Edgebox-Org':aOrg})).status,200);assert.equal((await b.call('/dashboard','GET',undefined,{'X-Edgebox-Org':aOrg})).status,403);});
test('an organisation must keep at least one owner',async()=>{const a=fixture();await a.login('business','A');const aOrg=a.getOrg();assert.equal((await a.call('/members/person@gmail.com/remove','POST',{},{'X-Edgebox-Org':aOrg})).status,409);});
test('partner delegation is scoped read plus acknowledge, never write, and revocation is immediate',async()=>{const store=new MemoryStorage();const a=fixture(store,'sub-a','a@gmail.com');const x=await source(a);const aOrg=a.getOrg();await a.call('/events','POST',event(),{Authorization:`Bearer ${x.key.api_key}`});const p=fixture(store,'sub-p','p@gmail.com');await p.signin();assert.equal((await a.call('/delegations','POST',{email:'p@gmail.com',scope:'verify'},{'X-Edgebox-Org':aOrg})).status,201);assert.equal((await p.call('/dashboard','GET',undefined,{'X-Edgebox-Org':aOrg})).status,200);assert.equal((await p.call('/events/evt_1/acknowledge','POST',{source_id:x.source.id},{'X-Edgebox-Org':aOrg})).status,200);assert.equal((await p.call('/sites','POST',{name:'X',kind:'home'},{'X-Edgebox-Org':aOrg})).status,403);assert.ok((await p.call('/delegated')).data.delegated.some(o=>o.orgId===aOrg));assert.equal((await a.call('/delegations/p@gmail.com/revoke','POST',{},{'X-Edgebox-Org':aOrg})).status,200);assert.equal((await p.call('/dashboard','GET',undefined,{'X-Edgebox-Org':aOrg})).status,403);});
test('delegation to an email without an Edgebox account is rejected',async()=>{const a=fixture();await a.login('business','A');const aOrg=a.getOrg();assert.equal((await a.call('/delegations','POST',{email:'nobody@gmail.com',scope:'verify'},{'X-Edgebox-Org':aOrg})).status,404);});
test('a member cannot grant delegations',async()=>{const store=new MemoryStorage();const a=fixture(store,'sub-a','a@gmail.com');await a.login('business','A');const aOrg=a.getOrg();await a.call('/members','POST',{email:'b@gmail.com',role:'member'});const b=fixture(store,'sub-b','b@gmail.com');await b.signin();const p=fixture(store,'sub-p','p@gmail.com');await p.signin();assert.equal((await b.call('/delegations','POST',{email:'p@gmail.com',scope:'verify'},{'X-Edgebox-Org':aOrg})).status,403);});
test('internal admin lists and reads any org; a signed-in non-listed user is denied',async()=>{const store=new MemoryStorage();const a=fixture(store,'sub-a','a@gmail.com');await a.login('business','A Org');const aOrg=a.getOrg();const admin=fixture(store,'sub-admin','admin@edgebox.africa',['sub-admin']);await admin.signin();const list=await admin.call('/admin/orgs');assert.equal(list.status,200);assert.ok(list.data.orgs.some(o=>o.orgId===aOrg));const one=await admin.call(`/admin/orgs/${aOrg}`);assert.equal(one.status,200);assert.equal(one.data.organisation.name,'A Org');const outsider=fixture(store,'sub-out','out@gmail.com',['sub-admin']);await outsider.signin();assert.equal((await outsider.call('/admin/orgs')).status,403);assert.equal((await outsider.call(`/admin/orgs/${aOrg}`)).status,403);});
