import test from 'node:test';
import assert from 'node:assert/strict';
import { application, digest } from '../server/app.ts';
class MemoryStorage {
  values=new Map(); revision=0;
  async read(key){const v=this.values.get(key);return v?structuredClone(v):null;}
  async write(key,data,etag){const old=this.values.get(key);if((old?.etag??null)!==etag)return false;this.values.set(key,{data:structuredClone(data),etag:String(++this.revision)});return true;}
}
function fixture(storage=new MemoryStorage(),email='owner@gmail.com'){
  let time=Date.parse('2026-09-15T12:00:00Z'), google={};
  const settings={origin:'https://edgebox.africa',ownerEmail:email,ownerCodeHash:digest(`private-${email}`),ownerCodeExpires:time+86400000,googleClientId:'test.apps.googleusercontent.com'};
  const app=application({storage,settings,now:()=>time,verifyGoogle:async token=>{if(token!=='verified-fixture')throw Error();return google;}});
  let cookie='',csrf='';
  const call=async(path,method='GET',body,extra={})=>{
    const response=await app(new Request(settings.origin+'/api/v1'+path,{method,headers:{Origin:settings.origin,Cookie:cookie,'Content-Type':'application/json','X-CSRF-Token':csrf,'Idempotency-Key':crypto.randomUUID(),...extra},...(body===undefined?{}:{body:JSON.stringify(body)})}),'127.0.0.1');
    return {status:response.status,data:await response.json(),response};
  };
  const login=async()=>{const r=await call('/auth/owner','POST',{code:`private-${email}`});assert.equal(r.status,200);cookie=r.response.headers.get('set-cookie').split(';')[0];csrf=r.data.csrf;return r;};
  return {storage,settings,call,login,app,setTime:v=>time=v,setGoogle:v=>google=v,getTime:()=>time};
}
async function source(f){await f.login();const site=await f.call('/sites','POST',{name:'Test site',kind:'business'});const s=await f.call('/sources','POST',{name:'Gateway',site_id:site.data.id,brand:'Webhook'});const key=await f.call('/api-keys','POST',{source_id:s.data.id});return {site:site.data,source:s.data,key:key.data};}
const event=(id='evt_1')=>({event_id:id,event_type:'connection.test',occurred_at:'2026-09-15T12:00:00Z'});
test('public health is real capability metadata and private dashboard rejects anonymous access',async()=>{const f=fixture();assert.equal((await f.call('/health')).status,200);assert.equal((await f.call('/dashboard')).status,401);assert.equal((await f.call('/auth/config')).data.account_signup,false);});
test('owner link establishes a secure session once and never accepts wrong codes',async()=>{const f=fixture();assert.equal((await f.call('/auth/owner','POST',{code:'wrong'})).status,401);const r=await f.login();assert.match(r.response.headers.get('set-cookie'),/Secure; HttpOnly; SameSite=Lax/);assert.equal((await f.call('/auth/owner','POST',{code:'private-owner@gmail.com'})).status,401);assert.equal((await f.call('/auth/session')).data.account.email,'owner@gmail.com');});
test('expired owner code and forged cookie are rejected',async()=>{const f=fixture();f.setTime(f.settings.ownerCodeExpires+1);assert.equal((await f.call('/auth/owner','POST',{code:'private-owner@gmail.com'})).status,401);assert.equal((await f.call('/dashboard','GET',undefined,{Cookie:'__Host-eb-session=forged'})).status,401);});
test('cross origin, missing origin and CSRF attacks fail',async()=>{const f=fixture();await f.login();for(const headers of [{Origin:'https://evil.test'},{Origin:''},{'X-CSRF-Token':'wrong'}])assert.equal((await f.call('/sites','POST',{name:'Bad',kind:'home'},headers)).status,403);});
test('logout revokes server-side session and expired sessions cannot be reused',async()=>{const f=fixture();await f.login();assert.equal((await f.call('/auth/logout','POST',{})).status,200);assert.equal((await f.call('/dashboard')).status,401);const g=fixture();await g.login();g.setTime(g.getTime()+43200001);assert.equal((await g.call('/dashboard')).status,401);});
test('site creates replay safely and conflicting idempotency payload fails',async()=>{const f=fixture();await f.login();const headers={'Idempotency-Key':'stable'},data={name:'Depot',kind:'business'};const one=await f.call('/sites','POST',data,headers),two=await f.call('/sites','POST',data,headers);assert.equal(one.data.id,two.data.id);assert.equal((await f.call('/sites','POST',{...data,name:'Other'},headers)).status,409);assert.equal((await f.call('/dashboard')).data.sites.length,1);});
test('concurrent writes retain both updates with compare-and-swap',async()=>{const f=fixture();await f.login();const result=await Promise.all(['A','B','C'].map(name=>f.call('/sites','POST',{name,kind:'home'})));assert.ok(result.every(r=>r.status===201));assert.equal((await f.call('/dashboard')).data.sites.length,3);});
test('separate accounts cannot create a source on another account site',async()=>{const store=new MemoryStorage(),a=fixture(store),b=fixture(store,'another@gmail.com');const x=await source(a);await b.login();assert.equal((await b.call('/sources','POST',{name:'Bad',site_id:x.site.id})).status,404);assert.equal((await b.call('/dashboard')).data.sites.length,0);});
test('new source is awaiting events and API key is excluded from dashboard and export',async()=>{const f=fixture(),x=await source(f);const data=(await f.call('/dashboard')).data;assert.equal(data.sources[0].status,'awaiting_events');assert.ok(!JSON.stringify(data).includes(x.key.api_key));assert.ok(!JSON.stringify((await f.call('/export')).data).includes(digest(x.key.api_key)));});
test('external events persist once, replay safely and conflict on changed payload',async()=>{const f=fixture(),x=await source(f),h={Authorization:`Bearer ${x.key.api_key}`};const a=await f.call('/events','POST',event(),h);assert.equal(a.status,200);assert.equal(a.data.accepted,true);assert.equal((await f.call('/events','POST',event(),h)).data.duplicate,true);assert.equal((await f.call('/events','POST',{...event(),event_type:'camera.offline'},h)).status,409);const d=(await f.call('/dashboard')).data;assert.equal(d.events.length,1);assert.equal(d.sources[0].status,'receiving_events');assert.equal(d.usage.amount_due_minor,0);});
test('revoked keys cannot write and event body cannot change credential scope',async()=>{const f=fixture(),x=await source(f),h={Authorization:`Bearer ${x.key.api_key}`};assert.equal((await f.call('/events','POST',{...event(),source_id:'spoofed'},h)).status,400);assert.equal((await f.call(`/api-keys/${x.key.id}/revoke`,'POST',{})).status,200);assert.equal((await f.call('/events','POST',event(),h)).status,401);});
test('event acknowledgement is persistent and tenant scoped',async()=>{const f=fixture(),x=await source(f);await f.call('/events','POST',event(),{Authorization:`Bearer ${x.key.api_key}`});assert.equal((await f.call('/events/evt_1/acknowledge','POST',{source_id:x.source.id})).status,200);assert.ok((await f.call('/dashboard')).data.events[0].acknowledgedAt);});
test('malformed timestamps, raw imagery and oversized requests rejected',async()=>{const f=fixture(),x=await source(f),h={Authorization:`Bearer ${x.key.api_key}`};for(const v of [{...event(),occurred_at:'2026-02-30T12:00:00Z'},{...event(),image:'sensitive'},{...event(),duration_seconds:-1}])assert.equal((await f.call('/events','POST',v,h)).status,400);assert.equal((await f.call('/events','POST',{...event(),blob:'x'.repeat(33000)},h)).status,413);});
test('service requests save intent but never create a payment or subscription',async()=>{const f=fixture(),x=await source(f);const r=await f.call('/service-requests','POST',{site_id:x.site.id,service:'camera-connection'});assert.equal(r.status,201);const d=(await f.call('/dashboard')).data;assert.equal(d.requests.length,1);assert.equal(d.usage.plan,'No paid subscription');assert.equal(d.capabilities.payments,false);});
test('Google uses one-time nonce, expected audience, verified owner email and validated credential',async()=>{const f=fixture();const challenge=await f.call('/auth/challenge','POST',{}), c=challenge.response.headers.get('set-cookie').split(';')[0];const claims={iss:'https://accounts.google.com',aud:f.settings.googleClientId,exp:f.getTime()/1000+3600,sub:'google-owner-subject',email:'owner@gmail.com',email_verified:true,nonce:challenge.data.nonce};f.setGoogle(claims);const result=await f.call('/auth/google','POST',{credential:'verified-fixture'},{Cookie:c});assert.equal(result.status,200);assert.equal((await f.call('/auth/google','POST',{credential:'verified-fixture'},{Cookie:c})).status,401);});
test('Google rejects unverified tokens, wrong audience, nonce, owner and expired claims',async()=>{for(const patch of [{aud:'other'},{nonce:'other'},{email_verified:false},{exp:1},{email:'attacker@gmail.com'},{iss:'https://evil.test'}]){const f=fixture(),challenge=await f.call('/auth/challenge','POST',{}),c=challenge.response.headers.get('set-cookie').split(';')[0];f.setGoogle({iss:'https://accounts.google.com',aud:f.settings.googleClientId,exp:f.getTime()/1000+3600,sub:'sub',email:'owner@gmail.com',email_verified:true,nonce:challenge.data.nonce,...patch});assert.ok([401,403].includes((await f.call('/auth/google','POST',{credential:'verified-fixture'},{Cookie:c})).status));assert.equal((await f.call('/auth/google','POST',{credential:'forged'},{Cookie:c})).status,401);}});
test('storage failure never produces a false successful save',async()=>{const f=fixture();await f.login();f.storage.write=async()=>{throw Error('backend offline');};const r=await f.call('/sites','POST',{name:'Depot',kind:'business'});assert.equal(r.status,503);assert.ok(!JSON.stringify(r.data).includes('backend offline'));});
