import React, { useEffect, useRef, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { safeReturnTo } from '../lib/returnTo.mjs';
import './AccountApp.css';

async function request(path, data, csrf, key, org) {
  const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000);
  try{
    const response=await fetch(`/api/v1${path}`,{method:data===undefined?'GET':'POST',credentials:'same-origin',signal:controller.signal,headers:{'Content-Type':'application/json',...(csrf?{'X-CSRF-Token':csrf}:{}),...(org?{'X-Edgebox-Org':org}:{}),'Idempotency-Key':key || crypto.randomUUID()},...(data===undefined?{}:{body:JSON.stringify(data)})});
    const result=await response.json();if(!response.ok){const error=new Error(result.error || 'Please try again.');error.status=response.status;throw error;}return result;
  }catch(error){if(error.name==='AbortError')throw new Error('The request timed out. Refresh to check whether it was saved before trying again.');throw error;}finally{clearTimeout(timer);}
}
export function SignIn(){
  const navigate=useNavigate(),button=useRef(null);
  const [config,setConfig]=useState(null),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);
  const target=safeReturnTo(new URLSearchParams(window.location.search).get('returnTo'));
  useEffect(()=>{
    let active=true;
    request('/auth/session').then(()=>{if(active)navigate(target,{replace:true});}).catch(()=>{});
    request('/auth/config').then(c=>{if(active)setConfig(c);}).catch(()=>{if(active)setStatus('Sign-in is temporarily unavailable. Please try again.');});
    return()=>{active=false;};
  },[navigate,target]);
  useEffect(()=>{
    if(!config?.google_enabled)return;
    let active=true,timer;
    const render=async()=>{
      if(!active || !button.current)return;
      if(!window.google?.accounts?.id){timer=setTimeout(render,150);return;}
      try{
        const {nonce}=await request('/auth/challenge',{});if(!active)return;
        window.google.accounts.id.initialize({client_id:config.google_client_id,nonce,auto_select:false,callback:async response=>{
          setBusy(true);setStatus('');try{await request('/auth/google',{credential:response.credential});navigate(target,{replace:true});}catch(e){setStatus(e.message);}finally{setBusy(false);}
        }});
        window.google.accounts.id.renderButton(button.current,{theme:'outline',size:'large',text:'continue_with',width:280});
      }catch(e){if(active)setStatus(e.message);}
    };
    let script=document.querySelector('script[data-edgebox-google]');
    if(!script){script=document.createElement('script');script.src='https://accounts.google.com/gsi/client';script.async=true;script.dataset.edgeboxGoogle='true';script.onerror=()=>{if(active)setStatus('Google could not load. Check your connection and try again.');};document.head.append(script);}
    render();const deadline=setTimeout(()=>{clearTimeout(timer);if(active && !window.google?.accounts?.id)setStatus('Google could not load. Refresh to try again.');},12000);
    return()=>{active=false;clearTimeout(timer);clearTimeout(deadline);};
  },[config,navigate,target]);
  return <main className="eb-account eb-signin"><Link to="/" className="eb-logo">EDGEBOX</Link><section className="eb-panel"><p className="eb-eyebrow">YOUR ACCOUNT</p><h1>Welcome to Edgebox.</h1><p>Sign in to manage your sites, connections and events.</p><div ref={button} aria-label="Sign in with Google" />{config && !config.google_enabled && <p>Sign-in is not available yet. Please check back shortly.</p>}<p role="status" aria-live="polite">{status}</p><p className="eb-small">New here? Signing in creates your account. <a href="mailto:support@edgebox.africa">Contact support</a>.</p><div className="eb-links"><Link to="/privacy-policy">Privacy</Link><Link to="/terms-of-service">Terms</Link></div></section></main>;
}
function Onboarding({onCreate,busy,status,onCancel}){
  const [type,setType]=useState('home'),[name,setName]=useState('');
  return <main className="eb-account eb-signin"><Link to="/" className="eb-logo">EDGEBOX</Link><section className="eb-panel"><p className="eb-eyebrow">GET STARTED</p><h1>What are you setting up?</h1><p>This creates your workspace. You can change the name later.</p><form onSubmit={e=>{e.preventDefault();onCreate(type,name.trim()||(type==='home'?'My home':'My business'));}}><div className="eb-choice">{[['home','My home','Cameras and alerts for where I live'],['business','My business','Sites, sources and events for my organisation']].map(([value,title,desc])=><label key={value} className={type===value?'eb-selected':''}><input type="radio" name="type" value={value} checked={type===value} onChange={()=>setType(value)} /><span className="eb-choicetext"><strong>{title}</strong><span>{desc}</span></span></label>)}</div><label>Name<input value={name} onChange={e=>setName(e.target.value)} maxLength={120} placeholder={type==='home'?'My home':'My business'} /></label><div className="eb-actions"><button className="eb-primary" disabled={busy}>{busy?'Creating…':'Create workspace'}</button>{onCancel && <button type="button" disabled={busy} onClick={onCancel}>Back to dashboard</button>}</div></form><p role="status" aria-live="polite">{status}</p></section></main>;
}
export default function AccountApp(){
  const navigate=useNavigate();
  const [session,setSession]=useState(null),[orgs,setOrgs]=useState([]),[activeOrg,setActiveOrg]=useState(''),[needsOnboarding,setNeedsOnboarding]=useState(false);
  const [data,setData]=useState(null),[tab,setTab]=useState('sites'),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[issuedKey,setIssuedKey]=useState(null);
  const [siteName,setSiteName]=useState(''),[kind,setKind]=useState('business'),[siteId,setSiteId]=useState(''),[sourceName,setSourceName]=useState(''),[brand,setBrand]=useState(''),[sourceId,setSourceId]=useState(''),[service,setService]=useState('camera-connection');
  async function refresh(org=activeOrg){if(!org)return;const d=await request('/dashboard',undefined,undefined,undefined,org);setData(d);setSiteId(old=>d.sites.some(s=>s.id===old)?old:d.sites[0]?.id || '');setSourceId(old=>d.sources.some(s=>s.id===old)?old:d.sources[0]?.id || '');}
  useEffect(()=>{let active=true;request('/auth/session').then(async s=>{if(!active)return;setSession(s);setOrgs(s.orgs||[]);if(s.onboarding || !(s.orgs||[]).length){setNeedsOnboarding(true);return;}const org=s.default_org_id || s.orgs[0].org_id;setActiveOrg(org);await refresh(org);}).catch(e=>{if(!active)return;if(e.status===401)navigate('/signin',{replace:true});else setStatus(e.message);});return()=>{active=false;};},[navigate]);
  async function perform(fn){setBusy(true);setStatus('');try{await fn();}catch(e){if(e.status===401)navigate('/signin',{replace:true});else if(e.status===403){setStatus('This workspace is no longer available to you.');}else setStatus(e.message);}finally{setBusy(false);}}
  const save=(path,body)=>request(path,body,session?.csrf,undefined,activeOrg);
  async function createOrg(type,name){await perform(async()=>{const created=await request('/onboarding',{type,name},session?.csrf);const next=[...orgs,{org_id:created.org_id,type:created.type,name:created.name,role:created.role}];setOrgs(next);setActiveOrg(created.org_id);setNeedsOnboarding(false);await refresh(created.org_id);setStatus('Workspace created. Add your first site.');});}
  async function switchOrg(org){setActiveOrg(org);setData(null);setIssuedKey(null);setStatus('');await perform(()=>refresh(org));}
  async function exportData(){const value=await request('/export',undefined,undefined,undefined,activeOrg),url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download='edgebox-account-export.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus('Your export is ready. API secrets are not included.');}
  const label=id=>data?.sites.find(s=>s.id===id)?.name || 'Site';
  const siteOptions=()=>data?.sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>);
  if(needsOnboarding)return <Onboarding onCreate={createOrg} busy={busy} status={status} onCancel={orgs.length>0?()=>{setNeedsOnboarding(false);setStatus('');}:undefined} />;
  return <div className="eb-account"><header className="eb-header"><Link to="/" className="eb-logo">EDGEBOX</Link>{orgs.length>=1 && <select className="eb-orgswitch" value={activeOrg} onChange={e=>e.target.value==='__new__'?setNeedsOnboarding(true):switchOrg(e.target.value)} aria-label="Switch or add workspace">{orgs.map(o=><option key={o.org_id} value={o.org_id}>{o.name}</option>)}<option value="__new__">+ New workspace…</option></select>}<span>{session?.account.email}</span><button disabled={busy} onClick={()=>perform(async()=>{await save('/auth/logout',{});setIssuedKey(null);navigate('/signin',{replace:true});})}>Sign out</button></header><div className="eb-layout"><nav className="eb-nav" aria-label="Account navigation">{[['sites','Sites'],['events','Events'],['api','API keys'],['billing','Usage & billing'],['requests','Requests']].map(([id,title])=><button key={id} aria-current={tab===id?'page':undefined} onClick={()=>{setTab(id);setStatus('');}}>{title}</button>)}<a href="/docs/api">API guide</a><button disabled={busy || !data} onClick={()=>perform(exportData)}>Export my data</button></nav><main className="eb-main"><div className="eb-title"><div><p className="eb-eyebrow">{data?.organisation?.name || 'YOUR WORKSPACE'}</p><h1>{tab==='sites'?'Your sites':tab==='events'?'Events':tab==='api'?'API keys':tab==='billing'?'Usage & billing':'Service requests'}</h1></div><button disabled={busy || !session} onClick={()=>perform(()=>refresh())}>Refresh</button></div><p className="eb-status" role="status" aria-live="polite">{status}</p>{!data?<p>{status?'The dashboard could not load. Use Refresh to try again.':'Loading your account…'}</p>:<>
      {tab==='sites' && <><div className="eb-stats"><div><strong>{data.sites.length}</strong><span>Sites</span></div><div><strong>{data.sources.length}</strong><span>Sources</span></div><div><strong>{data.sources.filter(s=>s.status==='receiving_events').length}</strong><span>Sending events</span></div></div><section className="eb-panel"><h2>Add a site</h2><form onSubmit={e=>{e.preventDefault();perform(async()=>{await save('/sites',{name:siteName,kind});setSiteName('');await refresh();setStatus('Site saved. Add a source next.');});}}><label>Site name<input value={siteName} onChange={e=>setSiteName(e.target.value)} maxLength={120} required placeholder="e.g. Cape Town warehouse" /></label><label>Type<select value={kind} onChange={e=>setKind(e.target.value)}><option value="business">Business</option><option value="home">Home</option></select></label><button className="eb-primary" disabled={busy}>Save site</button></form></section>{data.sites.length>0 && <section className="eb-panel"><h2>Add a source</h2><p>A source is a camera, recorder or integration. Adding one does not connect a camera automatically.</p><form onSubmit={e=>{e.preventDefault();perform(async()=>{await save('/sources',{site_id:siteId,name:sourceName,brand:brand || 'Other'});setSourceName('');await refresh();setStatus('Source saved. Create an API key to send events, or request help connecting your cameras.');});}}><label>Site<select value={siteId} onChange={e=>setSiteId(e.target.value)}>{siteOptions()}</select></label><label>Source name<input required maxLength={120} value={sourceName} onChange={e=>setSourceName(e.target.value)} placeholder="Front gate" /></label><label>Brand or integration<input maxLength={80} value={brand} onChange={e=>setBrand(e.target.value)} placeholder="Camera brand or gateway" /></label><button disabled={busy} className="eb-primary">Save source</button></form></section>}<section className="eb-panel"><h2>Connections</h2>{!data.sources.length?<p>No sources yet. Add your first site and source above.</p>:data.sources.map(s=><article className="eb-row" key={s.id}><div><strong>{s.name}</strong><p>{label(s.siteId)} · {s.brand}</p></div><span className="eb-badge">{s.status==='awaiting_events'?'Awaiting events':s.status==='stale'?'No recent events':'Receiving events'}</span></article>)}</section></>}
      {tab==='events' && <section className="eb-panel"><p>Events received through your source API keys. These are source-reported signals, not Edgebox video analysis.</p>{!data.events.length?<div className="eb-empty"><h2>No events yet.</h2><p>Create a source and API key, then send an event using the API guide.</p><button onClick={()=>setTab('api')}>Set up an API key</button></div>:data.events.map(e=><article className="eb-row" key={e.sourceId+e.id}><div><strong>{e.event_type==='connection.test'?'Connection test':e.event_type.replaceAll('.',' ')}</strong><p>{label(e.siteId)} · {new Date(e.occurred_at).toLocaleString()}</p><small>Received {new Date(e.receivedAt).toLocaleString()}</small></div><button disabled={busy || Boolean(e.acknowledgedAt)} onClick={()=>perform(async()=>{await save(`/events/${encodeURIComponent(e.id)}/acknowledge`,{source_id:e.sourceId});await refresh();})}>{e.acknowledgedAt?'Acknowledged':'Acknowledge'}</button></article>)}</section>}
      {tab==='api' && <><section className="eb-panel"><h2>Connect a source to the API</h2><p>Keys can only submit metadata for the source you select. They cannot read your dashboard. Each key expires after 30 days.</p>{!data.sources.length?<button onClick={()=>setTab('sites')}>Add a source first</button>:<form onSubmit={e=>{e.preventDefault();perform(async()=>{const value=await save('/api-keys',{source_id:sourceId});setIssuedKey(value.api_key);await refresh();setStatus('Key created. Copy it now; it will not be shown again.');});}}><label>Source<select value={sourceId} onChange={e=>setSourceId(e.target.value)}>{data.sources.map(s=><option key={s.id} value={s.id}>{label(s.siteId)} — {s.name}</option>)}</select></label><button disabled={busy} className="eb-primary">Create API key</button></form>}{issuedKey && <div className="eb-secret"><label>Copy this key now<input readOnly value={issuedKey} onFocus={e=>e.target.select()} /></label><button onClick={()=>perform(async()=>{await navigator.clipboard.writeText(issuedKey);setStatus('API key copied. Keep it private.');})}>Copy key</button><button disabled={busy} onClick={()=>perform(async()=>{const response=await fetch('/api/v1/events',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${issuedKey}`},body:JSON.stringify({event_id:crypto.randomUUID(),event_type:'connection.test',occurred_at:new Date().toISOString()})});const result=await response.json();if(!response.ok)throw new Error(result.error || 'Connection test failed.');await refresh();setStatus('Connection test saved. Open Events to see it. This tests the API, not a physical camera.');})}>Send connection test</button><button onClick={()=>setIssuedKey(null)}>Hide key</button></div>}<p><a href="/docs/api">See the event format and a working request example →</a></p></section><section className="eb-panel"><h2>Issued keys</h2>{!data.keys.length?<p>No API keys.</p>:data.keys.map(k=><article className="eb-row" key={k.id}><div><strong>{data.sources.find(s=>s.id===k.sourceId)?.name || 'Source'}</strong><p>Expires {new Date(k.expires).toLocaleDateString()}</p></div><button disabled={busy || k.revoked} onClick={()=>perform(async()=>{await save(`/api-keys/${k.id}/revoke`,{});setIssuedKey(null);await refresh();})}>{k.revoked?'Revoked':'Revoke'}</button></article>)}</section></>}
      {tab==='billing' && <section className="eb-panel"><h2>{data.usage.plan}</h2><p className="eb-amount">{new Intl.NumberFormat('en-ZA',{style:'currency',currency:data.usage.currency}).format(data.usage.amount_due_minor/100)} due</p><p>{data.usage.events} of {data.usage.event_limit} stored events · {data.usage.sources} sources · {data.usage.sites} sites</p><p>No payment method is saved and no automatic charge is enabled. Camera installation and managed services need a separate quote.</p><button className="eb-primary" onClick={()=>setTab('requests')}>Request a plan</button></section>}
      {tab==='requests' && <><section className="eb-panel"><h2>What do you need?</h2>{!data.sites.length?<button onClick={()=>setTab('sites')}>Add a site first</button>:<form onSubmit={e=>{e.preventDefault();perform(async()=>{const result=await save('/service-requests',{site_id:siteId,service});await refresh();setStatus(`Request ${result.id.slice(0,8)} saved. You have not been charged. Email support with this reference to arrange the next step.`);});}}><label>Site<select value={siteId} onChange={e=>setSiteId(e.target.value)}>{siteOptions()}</select></label><label>Service<select value={service} onChange={e=>setService(e.target.value)}><option value="camera-connection">Help connecting cameras</option><option value="partner-platform">Security company / installer</option><option value="operations">A business workflow</option><option value="account-deletion">Delete my account</option></select></label><button className="eb-primary" disabled={busy}>Save request</button></form>}<p><a href="mailto:support@edgebox.africa">Email support@edgebox.africa</a></p></section><section className="eb-panel"><h2>Your requests</h2>{data.requests.length?data.requests.map(r=><article key={r.id} className="eb-row"><div><strong>{r.service.replaceAll('-',' ')}</strong><p>{label(r.siteId)} · {r.id.slice(0,8)}</p></div><span>{r.status}</span></article>):<p>No requests yet.</p>}</section></>}
    </>}</main></div></div>;
}
