import React, { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import './CommercialApp.css';

const StatusContext = React.createContext(()=>{});
const MONEY = new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR',maximumFractionDigits:2});
const money = value => MONEY.format((value || 0)/100);
const stamp = value => new Date(value).toLocaleDateString('en-ZA',{day:'numeric',month:'short',year:'numeric'});
const cents = value => { if(!/^\d+(?:\.\d{1,2})?$/.test(String(value)))throw new Error('Enter a rand amount with no more than two decimal places.');const [r,c='']=String(value).split('.');const n=Number(r)*100+Number(c.padEnd(2,'0'));if(!Number.isSafeInteger(n))throw new Error('Amount is too large.');return n; };
const toUTC = value => {const d=new Date(value);if(!Number.isFinite(d.getTime()))throw new Error('Choose a valid date and time.');return d.toISOString();};
const fields = {
 name:{label:'Company or household name',required:true,maxLength:120},
 evidenceRef:{label:'Evidence reference',placeholder:'Private document ID or clean HTTPS link',required:true,maxLength:500},
 dueAt:{label:'Next action due',type:'datetime-local',required:true},
 nextAction:{label:'Next action',placeholder:'Ask the operations manager about their current process',required:true,maxLength:300},
};
const stageNames={researched:'Research',qualified:'Qualified',proposal:'Quote prepared',contracted:'Agreement recorded',live:'Service active',ended:'Ended',lost:'Lost'};
const laneNames={partner:'Partner platform',operations:'Operations',home:'Home',business:'Business'};
async function api(path='',data,csrf,key) {
 const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),20000);
 try {const r=await fetch(`/api/v1${path}`,{method:data===undefined?'GET':'POST',credentials:'same-origin',signal:controller.signal,headers:{'Content-Type':'application/json',...(csrf?{'X-CSRF-Token':csrf}:{}),...(key?{'Idempotency-Key':key}:{})},...(data===undefined?{}:{body:JSON.stringify(data)})});const payload=await r.json();if(!r.ok){const e=new Error(payload.error||'The request failed.');e.status=r.status;throw e;}return payload;}
 catch(e){if(e.name==='AbortError')throw new Error('Save timed out. Retry the same action to check it safely; do not create a second payment reference.');throw e;}finally{clearTimeout(timeout);}
}
function Field({name,definition,defaultValue}){
 const id=`field-${React.useId()}`;
 return <label htmlFor={id}>{definition.label}{definition.options?<select id={id} name={name} defaultValue={defaultValue??''} required={definition.required}>{!defaultValue&&<option value="">Choose…</option>}{definition.options.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>:definition.type==='textarea'?<textarea id={id} name={name} rows={3} required={definition.required} maxLength={definition.maxLength||1000} placeholder={definition.placeholder} defaultValue={defaultValue||''}/>:<input id={id} name={name} type={definition.type||'text'} required={definition.required} maxLength={definition.maxLength||300} step={definition.type==='number'?'1':undefined} min={definition.type==='number'?'0':undefined} placeholder={definition.placeholder} defaultValue={defaultValue||''}/>}{definition.hint&&<small>{definition.hint}</small>}</label>;
}
function Form({definitions,onSave,label,busy,defaults={},children}){
 const report=React.useContext(StatusContext);
 return <form onSubmit={e=>{e.preventDefault();try{Promise.resolve(onSave(Object.fromEntries(new FormData(e.currentTarget)))).catch(e=>report(e.message));}catch(e){report(e.message);}}}><fieldset disabled={busy}><div className="ce-form-grid">{Object.entries(definitions).map(([key,value])=><Field key={key} name={key} definition={value} defaultValue={defaults[key]}/>)}</div>{children}<button className="ce-primary" type="submit">{busy?'Saving…':label}</button></fieldset></form>;
}
function Metric({label,value,detail}){return <article className="ce-metric"><p>{label}</p><strong>{value}</strong><small>{detail}</small></article>;}
function Empty({title,children}){return <div className="ce-empty"><h3>{title}</h3><p>{children}</p></div>;}
function Opportunity({deal,account,command,busy,refreshStatus}){
 const d=deal,q=d.quotes.at(-1),[panel,setPanel]=useState('next'),[showQuote,setShowQuote]=useState(false);
 useEffect(()=>{setPanel('next');setShowQuote(false);},[d.id]);
 const next={researched:'qualify',qualified:'quote',proposal:'contract',contracted:'receipt',live:'renewal'}[d.stage];
 const send=(type,payload)=>command(type,{id:d.id,...payload});
 const draft=()=>{
  if(!q)return;
  const text=`DRAFT — not sent\nEdgebox proposal for ${account.name}\n${d.title}\n\nScope: ${q.scope}\n\n${q.lines.map(l=>`${l.label}: ${l.quantity} × ${money(l.unitMinor)} (${l.cadence})`).join('\n')}\nOne-off: ${money(q.onceMinor)}\nMonthly equivalent: ${money(q.monthlyMinor)}\nAmounts exclude applicable tax. This is not a tax invoice.\nValid until ${stamp(q.expiresAt)}.\n\nNo order, installation or payment is initiated by this draft. Final service and data terms require agreement.\n`;
  navigator.clipboard.writeText(text).then(()=>refreshStatus('Proposal draft copied. Nothing was sent.')).catch(()=>refreshStatus('Clipboard unavailable. Use Export to retrieve the quote.'));
 };
 return <section className="ce-deal"><div className="ce-deal-heading"><div><p className="ce-kicker">{account.name} {account.testRecord?'· TEST RECORD':''}</p><h2>{d.title}</h2></div><span className={`ce-pill ce-${d.stage}`}>{stageNames[d.stage]}</span></div>
  <ol className="ce-steps">{['researched','qualified','proposal','contracted','live'].map((s,i)=><li key={s} aria-current={d.stage===s?'step':undefined}><span>{i+1}</span>{stageNames[s]}</li>)}</ol>
  <p className="ce-muted">{laneNames[d.lane]} · Owner: {d.owner} · Contact: {account.permission.replaceAll('_',' ')}</p>
  <nav className="ce-segments" aria-label="Opportunity actions">{[['next','Next action'],['permission','Contact route'],[next,'Continue sale'],['history','Quote & receipts'],['blocker','Blocker']].filter(([id])=>id).map(([id,label])=><button key={id+label} className={panel===id?'is-active':''} onClick={()=>setPanel(id)}>{label}</button>)}</nav>
  {panel==='next'&&<Form key={d.id+':next'} definitions={{nextAction:fields.nextAction,dueAt:fields.dueAt,owner:{label:'Owner',required:true,maxLength:80}}} defaults={{nextAction:d.nextAction,owner:d.owner}} busy={busy} label="Save next action" onSave={p=>send('deal.next_action',{...p,dueAt:toUTC(p.dueAt)})}/>}
  {panel==='permission'&&<><p>Keep research separate from permission to contact. A public email address is not a recorded opt-in.</p><Form definitions={{permission:{label:'Contact route',required:true,options:[['research_only','Research only'],['consented','Consent recorded'],['existing_relationship','Existing relationship'],['do_not_contact','Do not contact']]},evidenceRef:fields.evidenceRef}} busy={busy} label="Save contact route" onSave={p=>command('account.permission',{id:account.id,...p})}/></>}
  {panel==='qualify'&&<><h3>Confirm a buyer and a problem worth paying for</h3><Form definitions={{buyerRole:{label:'Economic buyer role',placeholder:'Control-room manager',required:true,maxLength:100},problem:{label:'What does the customer need?',type:'textarea',required:true,maxLength:500},evidenceRef:fields.evidenceRef}} label="Mark as qualified" busy={busy} onSave={p=>send('deal.qualify',p)}/></>}
  {(panel==='quote'||showQuote)&&<><h3>Build a quote</h3><p className="ce-muted">Enter a deliberate price test, not the old camera-monitoring price assumption. All amounts below are in rand, excluding tax.</p><Form definitions={{description:{label:'Recurring service',required:true,placeholder:'Partner software — one site'},quantity:{label:'Quantity',type:'number',required:true},unit:{label:'Monthly price per unit (R)',required:true,placeholder:'Enter agreed or test price'},setup:{label:'One-off commissioning (R)',required:true},delivery:{label:'Estimated monthly delivery cost (R)',required:true},channel:{label:'Monthly partner/channel cost (R)',required:true},expiresAt:{label:'Quote expires',type:'datetime-local',required:true},scope:{label:'Included scope and exclusions',type:'textarea',required:true,maxLength:1000},exceptionRef:{label:'Negative-margin exception reference',placeholder:'Only needed if contribution is negative'}}} defaults={{quantity:'1',setup:'0',channel:'0'}} busy={busy} label="Save quote draft" onSave={p=>send('quote.create',{lines:[{label:p.description,quantity:Number(p.quantity),unitMinor:cents(p.unit),cadence:'monthly'},...(cents(p.setup)?[{label:'Commissioning',quantity:1,unitMinor:cents(p.setup),cadence:'once'}]:[])],directCostMinor:cents(p.delivery),channelCostMinor:cents(p.channel),expiresAt:toUTC(p.expiresAt),scope:p.scope,exceptionRef:p.exceptionRef})}/></>}
  {panel==='contract'&&<><h3>Record the signed agreement</h3><p>{q?`${money(q.monthlyMinor)}/month equivalent + ${money(q.onceMinor)} once. Valid until ${stamp(q.expiresAt)}.`:'Prepare a quote first.'}</p><Form definitions={{evidenceRef:{...fields.evidenceRef,label:'Signed agreement reference'}}} busy={busy} label="Record agreement" onSave={p=>send('contract.record',{quoteId:q?.id,...p})}/><button onClick={()=>setShowQuote(!showQuote)}>Prepare a revised quote instead</button></>}
  {panel==='receipt'&&<><h3>Record collected money</h3><p>Use a bank or payment-provider reference and supporting evidence. This records a receipt; it does not charge the customer.</p><Form definitions={{reference:{label:'Unique settlement reference',required:true,maxLength:120},gross:{label:'Amount received, including tax (R)',required:true},tax:{label:'Tax included (R)',required:true},category:{label:'What is the payment for?',required:true,options:[['service','Service'],['deposit','Refundable deposit'],['hardware','Hardware'],['pass_through','Third-party pass-through']]},paidAt:{label:'Settlement date',type:'datetime-local',required:true},evidenceRef:fields.evidenceRef}} defaults={{tax:'0'}} busy={busy} label="Record receipt" onSave={p=>send('receipt.record',{reference:p.reference,grossMinor:cents(p.gross),taxMinor:cents(p.tax),category:p.category,paidAt:toUTC(p.paidAt),evidenceRef:p.evidenceRef})}/><button onClick={()=>setPanel('activate')}>Service paid and installed? Record activation →</button></>}
  {panel==='activate'&&<><h3>Confirm delivery before counting MRR</h3><Form definitions={{sites:{label:'Unique commissioned site IDs',type:'textarea',hint:'One per line. Use the same ID used in the product dashboard.',required:true},startedAt:{label:'Service started',type:'datetime-local',required:true},renewalAt:{label:'Next renewal review',type:'datetime-local',required:true},acceptanceRef:{...fields.evidenceRef,label:'Buyer acceptance reference'},commissioningRef:{...fields.evidenceRef,label:'Commissioning evidence'}}} label="Record active service" busy={busy} onSave={p=>send('activation.record',{siteRefs:p.sites.split('\n').map(x=>x.trim()).filter(Boolean),startedAt:toUTC(p.startedAt),renewalAt:toUTC(p.renewalAt),acceptanceRef:p.acceptanceRef,commissioningRef:p.commissioningRef})}/></>}
  {panel==='renewal'&&<><h3>Service and renewal</h3><p>{d.activation.siteRefs.length} sites · {money(d.activation.monthlyMinor)}/month · Review by {stamp(d.activation.renewalAt)}</p><p>Record new period receipts under Quote & receipts. For a new price or renewal agreement, create a new opportunity after ending this one; site attribution cannot overlap.</p><details><summary>End this service</summary><Form definitions={{endedAt:{label:'Service ended',type:'datetime-local',required:true},reason:{label:'Reason',required:true},evidenceRef:fields.evidenceRef}} busy={busy} label="Record service end" onSave={p=>send('service.end',{...p,endedAt:toUTC(p.endedAt)})}/></details></>}
  {panel==='history'&&<><h3>Commercial record</h3>{q?<div className="ce-quote"><p className="ce-kicker">LATEST QUOTE · VERSION {q.version}</p><strong>{money(q.monthlyMinor)}<small> / month equivalent</small></strong><p>{money(q.onceMinor)} once · {money(q.contributionMinor)} estimated monthly contribution</p><p>{q.scope}</p><button onClick={draft}>Copy proposal draft</button></div>:<p>No quote prepared.</p>}<p>{d.quotes.length} quote versions · {d.contract?'Agreement recorded':'No agreement recorded'}</p>{d.receipts.map(r=><article className="ce-row" key={r.id}><div><strong>{r.reference}</strong><p>{r.category.replaceAll('_',' ')} · {stamp(r.paidAt)} · operator recorded</p></div><strong>{r.kind==='refund'?'-':''}{money(r.grossMinor)}</strong></article>)}{d.contract&&<button onClick={()=>setPanel('receipt')}>Record another receipt</button>}{d.receipts.some(r=>r.kind==='receipt')&&<details><summary>Record a settled refund</summary><Form definitions={{receiptId:{label:'Original receipt',required:true,options:d.receipts.filter(r=>r.kind==='receipt').map(r=>[r.id,r.reference])},reference:{label:'Unique refund reference',required:true},gross:{label:'Refund amount incl. tax (R)',required:true},tax:{label:'Tax refunded (R)',required:true},paidAt:{label:'Refund settlement date',type:'datetime-local',required:true},evidenceRef:fields.evidenceRef}} defaults={{tax:'0'}} busy={busy} label="Record refund (does not move money)" onSave={p=>send('receipt.refund',{receiptId:p.receiptId,reference:p.reference,grossMinor:cents(p.gross),taxMinor:cents(p.tax),paidAt:toUTC(p.paidAt),evidenceRef:p.evidenceRef})}/></details>}</>}
  {panel==='blocker'&&<><Form definitions={{reason:{label:'What is blocked?',required:true,maxLength:300},humanOnly:{label:'Who must act?',required:true,options:[['false','Agent or team can resolve'],['true','Only Bongani can resolve']]},evidenceRef:fields.evidenceRef}} busy={busy} label="Record blocker" onSave={p=>send('deal.blocker',{...p,humanOnly:p.humanOnly==='true'})}/>{d.blocker&&<button disabled={busy} onClick={()=>send('deal.blocker',{reason:''})}>Mark blocker resolved</button>}</>}
  {!['live','ended','lost'].includes(d.stage)&&<details className="ce-close-deal"><summary>Close as lost</summary><Form definitions={{reason:{label:'Why did we lose?',required:true}}} busy={busy} label="Close opportunity" onSave={p=>send('deal.lose',p)}/></details>}
 </section>;
}
const RND_STAGES={idea:'Idea',designed:'Designed',running:'Running',measured:'Measured',decided:'Decided'};
const RND_GATES={r100k:'R100k/mo',r1m:'R1M/mo',r10m:'R10M/mo',r100m:'R100M/mo'};
function Login({onDone}){
 const [email,setEmail]=useState('info@Khuselaworkflow.com'),[password,setPassword]=useState(''),[otp,setOtp]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 return <main className="ce-app ce-gate"><p className="ce-kicker">EDGEBOX COMMERCIAL</p><h1>Operator sign-in</h1><p>Email, password and your authenticator code.</p>
  <form onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setMsg('');try{await api('/admin/login',{email:email.trim(),password,otp:otp.trim()});onDone();}catch(err){setMsg(err.message);}finally{setBusy(false);}}}>
   <label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="username"/></label>
   <label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password"/></label>
   <label>Authenticator code<input value={otp} onChange={e=>setOtp(e.target.value)} inputMode="numeric" pattern="\d{6}" maxLength={6} required autoComplete="one-time-code" placeholder="123456"/></label>
   <button className="ce-primary" disabled={busy}>{busy?'Checking…':'Sign in'}</button>
  </form><p role="status" aria-live="polite">{msg}</p><Link to="/app">Customer dashboard</Link></main>;
}
function RndCard({exp,busy,onPatch,onDelete}){
 const [result,setResult]=useState(exp.result||'');
 return <article className="rnd-card"><h4>{exp.title}</h4><p className="rnd-hyp">{exp.hypothesis}</p><p className="rnd-test"><span>Cheapest test</span>{exp.cheapest_test}</p><p className="ce-muted">{money(exp.cost_minor)} · {RND_GATES[exp.gate]}</p>
  <div className="rnd-controls"><label>Stage<select value={exp.stage} disabled={busy} onChange={e=>onPatch({stage:e.target.value})}>{Object.entries(RND_STAGES).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Decision<select value={exp.decision||''} disabled={busy} onChange={e=>onPatch({decision:e.target.value})}><option value="">Undecided</option><option value="pursue">Pursue</option><option value="kill">Kill</option><option value="iterate">Iterate</option></select></label></div>
  <div className="rnd-result"><input value={result} onChange={e=>setResult(e.target.value)} maxLength={2000} placeholder="What did the test show?"/><button disabled={busy} onClick={()=>onPatch({result})}>Save</button></div>
  <button className="rnd-delete" disabled={busy} onClick={onDelete}>Delete</button></article>;
}
function RndBoard({csrf,report}){
 const [board,setBoard]=useState(null),[busy,setBusy]=useState(false);
 const [form,setForm]=useState({title:'',hypothesis:'',cheapest_test:'',cost:'',gate:'r100k'}),[mrr,setMrr]=useState('');
 const live=useRef(true);
 const load=async()=>{const b=await api('/admin/rnd');if(live.current){setBoard(b);setMrr(String((b.gates.current_mrr_minor||0)/100));}};
 useEffect(()=>{live.current=true;load().catch(e=>report(e.message));return()=>{live.current=false;};},[]);
 const act=async fn=>{if(busy)return;setBusy(true);try{await fn();await load();}catch(e){report(e.message);}finally{setBusy(false);}};
 if(!board)return <p role="status">Loading experiments…</p>;
 const cur=board.gates.current_mrr_minor||0,next=board.gates.targets.find(t=>t.target_minor>cur)||board.gates.targets[board.gates.targets.length-1];
 return <>
  <section className="ce-card"><div className="ce-section-title"><div><h2>Revenue gates</h2><p>Each experiment is a bet on reaching the next gate. Update MRR as it changes.</p></div></div>
   <div className="rnd-gates">{board.gates.targets.map(t=>{const reached=cur>=t.target_minor;return <div key={t.key} className={`rnd-gate${reached?' is-reached':''}${t.key===next.key&&!reached?' is-next':''}`}><strong>{RND_GATES[t.key]}</strong><span>{money(t.target_minor)}</span></div>;})}</div>
   <form className="rnd-mrr" onSubmit={e=>{e.preventDefault();act(()=>api('/admin/rnd/gates',{current_mrr_minor:cents(mrr),note:board.gates.note||''},csrf));}}><label>Current MRR (R)<input value={mrr} onChange={e=>setMrr(e.target.value)} inputMode="decimal"/></label><button className="ce-primary" disabled={busy}>Save MRR</button><span className="ce-muted">Next: {RND_GATES[next.key]} · {money(Math.max(0,next.target_minor-cur))} to go</span></form></section>
  <section className="ce-card"><h2>New experiment</h2><div className="rnd-add">
   <label>Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} maxLength={200} placeholder="Depot dwell-time pilot"/></label>
   <label>Hypothesis<input value={form.hypothesis} onChange={e=>setForm({...form,hypothesis:e.target.value})} maxLength={1000} placeholder="A depot will pay R25k to cut queue dwell exceptions"/></label>
   <label>Cheapest test<input value={form.cheapest_test} onChange={e=>setForm({...form,cheapest_test:e.target.value})} maxLength={1000} placeholder="One paid 30-day pilot at one depot"/></label>
   <label>Cost (R)<input value={form.cost} onChange={e=>setForm({...form,cost:e.target.value})} inputMode="decimal" placeholder="25000"/></label>
   <label>Target gate<select value={form.gate} onChange={e=>setForm({...form,gate:e.target.value})}>{Object.entries(RND_GATES).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
   <button className="ce-primary" disabled={busy||!form.title.trim()||!form.hypothesis.trim()||!form.cheapest_test.trim()} onClick={()=>act(async()=>{await api('/admin/rnd/experiments',{title:form.title.trim(),hypothesis:form.hypothesis.trim(),cheapest_test:form.cheapest_test.trim(),cost_minor:form.cost?cents(form.cost):0,gate:form.gate},csrf);setForm({title:'',hypothesis:'',cheapest_test:'',cost:'',gate:'r100k'});report('Experiment added.');})}>Add experiment</button></div></section>
  <div className="rnd-board">{board.stages.map(stage=>{const cards=board.experiments.filter(e=>e.stage===stage);return <section className="rnd-col" key={stage}><h3>{RND_STAGES[stage]} <span>{cards.length}</span></h3>{cards.length?cards.map(exp=><RndCard key={exp.id} exp={exp} busy={busy} onPatch={p=>act(()=>api(`/admin/rnd/experiments/${exp.id}`,p,csrf))} onDelete={()=>act(()=>api(`/admin/rnd/experiments/${exp.id}/delete`,{},csrf))}/>):<p className="ce-muted">Empty</p>}</section>;})}</div>
 </>;
}
export default function CommercialApp(){
 const [data,setData]=useState(null),[session,setSession]=useState(null),[error,setError]=useState(''),[status,setStatus]=useState(''),[tab,setTab]=useState('today'),[busy,setBusy]=useState(false),[selected,setSelected]=useState(''),[adding,setAdding]=useState(false),[accountId,setAccountId]=useState(''),[search,setSearch]=useState('');
 const pending=useRef(null),live=useRef(true);
 async function refresh(){const next=await api('/commercial');if(live.current)setData(next);return next;}
 async function bootstrap(){setError('');try{const s=await api('/admin/session');if(live.current)setSession(s);await refresh();}catch(e){if(live.current)setError(e.status===401?'signin':e.status===403?'forbidden':e.message);}}
 useEffect(()=>{live.current=true;bootstrap();return()=>{live.current=false;};},[]);
 async function command(type,payload){
  if(busy)return;setBusy(true);setStatus('');
  try{const fingerprint=JSON.stringify({type,payload});if(!pending.current || pending.current.fingerprint!==fingerprint)pending.current={fingerprint,key:crypto.randomUUID(),body:{type,payload,revision:data.revision}};
   const p=pending.current,result=await api('/commercial/commands',p.body,session.csrf,p.key);pending.current=null;await refresh();setStatus('Saved.');if(type==='deal.create'){setSelected(result.result.id);setAdding(false);}if(type==='account.create'){setAccountId(result.result.id);setAdding('deal');}return result;
  }catch(e){if(e.status===401){setData(null);setError('signin');}else{setStatus(e.message);if(e.status===409){pending.current=null;await refresh().catch(()=>{});}}}finally{setBusy(false);}
 }
 const safely=fn=>values=>{try{Promise.resolve(fn(values)).catch(e=>setStatus(e.message));}catch(e){setStatus(e.message);}};
 const guardedCommand=(type,payload)=>command(type,payload);
 const accounts=data?.accounts||[],deals=data?.deals||[],selectedDeal=deals.find(d=>d.id===selected),selectedAccount=selectedDeal&&accounts.find(a=>a.id===selectedDeal.accountId);
 const accountName=id=>accounts.find(a=>a.id===id)?.name||'Account';
 const title={today:'What moves revenue today?',pipeline:'Your sales pipeline',partners:'Build a productive partner network',revenue:'Money, with evidence',procurement:'Procurement watchlist',rnd:'R&D experiments toward R100M/month',plan:'From first payment to R100M/month'}[tab];
 if(error==='signin')return <Login onDone={bootstrap}/>;
 if(error)return <main className="ce-app ce-gate"><p className="ce-kicker">EDGEBOX COMMERCIAL</p><h1>{error==='forbidden'?'This workspace is for Edgebox operators.':'The workspace could not load.'}</h1><p>{error==='forbidden'?'Customer and partner accounts cannot access the internal sales pipeline. An administrator must grant the internal role.':error}</p><Link to="/app">Customer dashboard</Link></main>;
 return <StatusContext.Provider value={setStatus}><div className="ce-app"><header className="ce-header"><Link to="/" className="ce-brand">EDGEBOX<span>Commercial</span></Link><span className="ce-header-note">Build the customer. Prove the revenue.</span><Link to="/app">Product dashboard ↗</Link></header><div className="ce-layout"><aside className="ce-sidebar"><p className="ce-kicker">REVENUE WORKSPACE</p><nav aria-label="Commercial navigation">{[['today','Today'],['pipeline','Pipeline'],['partners','Partners'],['revenue','Revenue'],['procurement','Procurement'],['rnd','R&D'],['plan','Growth plan']].map(([id,label])=><button key={id} aria-current={id===tab?'page':undefined} onClick={()=>{setTab(id);setSelected('');setAdding(false);setStatus('');}}>{label}{id==='today'&&data?.actions.length>0&&<span>{data.actions.length}</span>}</button>)}</nav><div className="ce-sidebar-goal"><small>THE DESTINATION</small><strong>R100M<span>/month</span></strong><p>A target, not a forecast.</p></div><button disabled={!data||busy} onClick={async()=>{try{const r=await api('/commercial/export'),url=URL.createObjectURL(new Blob([JSON.stringify(r,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='edgebox-commercial-private-export.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus('Export created. Keep it private.');}catch(e){setStatus(e.message);}}}>Export workspace</button></aside><main className="ce-main"><div className="ce-title"><div><p className="ce-kicker">{data?`AS OF ${stamp(data.asOf)}`:'EDGEBOX'}</p><h1>{title}</h1></div><button disabled={!data||busy} onClick={()=>refresh().catch(e=>setStatus(e.message))}>Refresh</button></div><p className="ce-status" role="status" aria-live="polite">{status}</p>
 {!data?<p role="status">Loading commercial records…</p>:<>
 {tab!=='rnd'&&<div className="ce-metrics"><Metric label="Activated MRR" value={money(data.metrics.activatedMrrMinor)} detail="Operator-recorded; current paid service only"/><Metric label="Recorded service collections" value={money(data.metrics.recordedServiceCashMinor)} detail="Net of tax and recorded refunds"/><Metric label="Qualified pipeline" value={money(data.metrics.qualifiedPipelineMrrMinor)} detail="Monthly quote value; not revenue"/><Metric label="Productive partners" value={data.metrics.productivePartners} detail={`${data.metrics.activatedSites} sites attributed to current service`}/></div>}
 {selectedDeal?<><button className="ce-back" onClick={()=>setSelected('')}>← Back to {tab}</button><ErrorBoundary key={selectedDeal.id} onError={setStatus}><Opportunity deal={selectedDeal} account={selectedAccount} command={guardedCommand} busy={busy} refreshStatus={setStatus}/></ErrorBoundary></>:<>
 {tab==='today'&&<div className="ce-two-column"><section className="ce-card"><div className="ce-section-title"><h2>Next actions</h2><button onClick={()=>{setTab('pipeline');setAdding('account');}}>Add a prospect</button></div>{!data.actions.length?<Empty title="Start with one qualified customer.">Add a researched account, record the contact route, and set the next action. No synthetic sales are loaded into this workspace.</Empty>:data.actions.map(a=><article className="ce-row" key={a.id}><div><span className="ce-pill">{a.kind.replaceAll('_',' ')}</span><h3>{a.title}</h3><p>{a.account} · {stamp(a.dueAt)}</p></div>{a.dealId&&<button onClick={()=>setSelected(a.dealId)}>Open →</button>}</article>)}</section><section className="ce-card ce-focus"><p className="ce-kicker">NEXT REVENUE GATE</p><h2>{money(data.metrics.nextGateMinor)}<small>/month</small></h2><p>Recruit → qualify → quote → agreement → payment → activation → renewal.</p><p>First prove one partner can sell and support the service. Then repeat.</p><button onClick={()=>setTab('plan')}>View the operating plan</button><hr/><h3>Evidence before headlines</h3><p>{data.basis}</p></section></div>}
 {(tab==='pipeline'||tab==='partners')&&<section className="ce-card"><div className="ce-section-title"><div><h2>{tab==='partners'?'Partner accounts':'Accounts & opportunities'}</h2><p>Every open opportunity needs an owner and a next action.</p></div><button className="ce-primary" onClick={()=>setAdding(adding?false:'account')}>{adding?'Close form':'+ Add prospect'}</button></div>
 {adding==='account'&&<Form definitions={{name:fields.name,domain:{label:'Company website',placeholder:'example.co.za'},kind:{label:'Account type',required:true,options:[['security_partner','Security company / installer'],['operations','Warehouse / operations'],['business','Business'],['home','Household']]},sourceRef:{...fields.evidenceRef,label:'Research source'},testRecord:{label:'Record purpose',required:true,options:[['false','Real researched prospect'],['true','Training / test — excluded from revenue']]}}} busy={busy} label="Save prospect" onSave={safely(p=>command('account.create',{...p,testRecord:p.testRecord==='true'}))}/>}
 {adding==='deal'&&<Form definitions={{accountId:{label:'Account',required:true,options:accounts.map(a=>[a.id,a.name])},title:{label:'Opportunity name',required:true,placeholder:'First three customer sites'},lane:{label:'Sales route',required:true,options:Object.entries(laneNames)},nextAction:fields.nextAction,dueAt:fields.dueAt,owner:{label:'Owner',required:true}}} defaults={{accountId,owner:'Bongani'}} busy={busy} label="Create opportunity" onSave={safely(p=>command('deal.create',{...p,dueAt:toUTC(p.dueAt)}))}/>}
 <input className="ce-search" aria-label="Search accounts and opportunities" placeholder="Find an account or opportunity…" value={search} onChange={e=>setSearch(e.target.value)}/>
 {!accounts.length?<Empty title="No prospects yet.">Add the first company you have researched. A prospect does not count as pipeline revenue.</Empty>:accounts.filter(a=>(tab!=='partners'||a.kind==='security_partner')&&(a.name+' '+a.domain).toLowerCase().includes(search.toLowerCase())).map(a=><article className="ce-account-row" key={a.id}><div className="ce-section-title"><div><h3>{a.name}{a.testRecord&&<span className="ce-pill">Test</span>}</h3><p>{a.domain||a.kind.replaceAll('_',' ')} · {a.permission.replaceAll('_',' ')}</p></div><button onClick={()=>{setAccountId(a.id);setAdding('deal');}}>+ Opportunity</button></div>{deals.filter(d=>d.accountId===a.id).map(d=><button className="ce-deal-link" key={d.id} onClick={()=>setSelected(d.id)}><span>{d.title}<small>{d.nextAction} · {stamp(d.dueAt)}</small></span><span className={`ce-pill ce-${d.stage}`}>{stageNames[d.stage]}</span><span>→</span></button>)}</article>)}
 </section>}
 {tab==='revenue'&&<section className="ce-card"><h2>Separate the promise from the payment</h2><p>Collections include only records entered with settlement evidence. MRR requires a signed quote, service payment, buyer acceptance, and commissioned sites. No bank connection or checkout is active here.</p><div className="ce-revenue-grid"><Metric label="All recorded collections" value={money(data.metrics.recordedCashMinor)} detail="Includes deposits/hardware; never treated as MRR"/><Metric label="Actual money movement" value="Not enabled" detail="Receipt and refund entries are records only"/></div>{!deals.some(d=>d.receipts.length)?<Empty title="No receipts recorded.">Open a contracted opportunity and record a settled payment with its evidence. Do not enter forecast sales as collections.</Empty>:deals.filter(d=>d.receipts.length).map(d=><article className="ce-row" key={d.id}><div><h3>{accountName(d.accountId)}</h3><p>{d.title} · {d.receipts.length} receipt/refund records</p></div><button onClick={()=>setSelected(d.id)}>Review records</button></article>)}</section>}
 {tab==='procurement'&&<section className="ce-card"><div className="ce-section-title"><div><h2>Tenders and procurement plans</h2><p>Unknown requirements stay unknown. A missed compulsory briefing blocks bidding.</p></div><button onClick={()=>setAdding(adding?false:'tender')}>{adding?'Close form':'Add opportunity'}</button></div>{adding==='tender'&&<Form definitions={{buyer:{label:'Buyer',required:true},reference:{label:'Tender reference',required:true},sourceRef:{...fields.evidenceRef,label:'Official source'},closesAt:{label:'Closes',type:'datetime-local',required:true},briefingAt:{label:'Compulsory briefing (if any)',type:'datetime-local'},partnerRequired:{label:'Delivery route',required:true,options:[['false','Assess direct eligibility'],['true','Requires an eligible prime / partner']]}}} busy={busy} label="Save procurement opportunity" onSave={safely(p=>command('tender.record',{...p,closesAt:toUTC(p.closesAt),briefingAt:p.briefingAt?toUTC(p.briefingAt):null,partnerRequired:p.partnerRequired==='true'}))}/>} {!data.tenders.length?<Empty title="No procurement records yet.">The daily briefing can surface official opportunities. Record only sourced opportunities, then check each mandatory requirement.</Empty>:data.tenders.map(t=><article className="ce-account-row" key={t.id}><div className="ce-section-title"><div><h3>{t.reference} · {t.buyer}</h3><p>Closes {stamp(t.closesAt)}</p></div><span className="ce-pill">{t.route.replaceAll('_',' ')}</span></div><details><summary>Review mandatory requirements</summary><p>Enter one requirement per line as <code>name | pass/fail/unknown | evidence reference</code>. A private ID is sufficient; do not paste documents.</p><Form definitions={{gates:{label:'Mandatory requirements',type:'textarea',required:true,maxLength:4000},briefingAttended:{label:'Compulsory briefing attended?',required:true,options:[['false','Not confirmed / not applicable'],['true','Attended with evidence']]},briefingEvidence:{label:'Briefing attendance evidence'},partnerRef:{label:'Partner commitment evidence (if required)'}}} busy={busy} label="Save eligibility review" onSave={safely(p=>command('tender.review',{id:t.id,gates:p.gates.split('\n').filter(x=>x.trim()).map(x=>{const [name,status,evidenceRef]=x.split('|').map(v=>v.trim());return {name,status,evidenceRef};}),briefingAttended:p.briefingAttended==='true',briefingEvidence:p.briefingEvidence,partnerRef:p.partnerRef}))}/></details></article>)}</section>}
 {tab==='plan'&&<section className="ce-card"><p className="ce-kicker">GATE-BASED OPERATING TARGETS</p><h2>First paid value. Then repeatable distribution.</h2><p>These windows are planning targets, not a revenue forecast. Start the clock when a deliverable offer and working activation path are ready.</p><div className="ce-roadmap">{[['First 30 days','First collected revenue','50 partner candidates → 15 conversations → 5 evaluations → 3 paid design partners targeted. Run one operations workflow alongside it.'],['By day 90','R100k–R250k MRR target','Prove repeat installations, delivery margin and retained customers. Count productive partners, not signed logos.'],['Months 6–9','R1M MRR target','Scale only channels with measured acquisition payback and low support burden.'],['Months 18–24','R10M MRR target','Partners commission independently. Add distributors and OEMs only after evidence of repeatability.'],['Months 48–72','R100M MRR ambition','A regional channel business, not a website milestone. Reforecast from actual cohorts every month.']].map(([window,goal,detail])=><article key={window}><p className="ce-kicker">{window}</p><h3>{goal}</h3><p>{detail}</p></article>)}</div><h3>Where the effort goes</h3><p>Partner platform first. Premium operations when value supports the price. Home remains a small conversion/support-cost experiment. No speculative hardware inventory.</p></section>}
 {tab==='rnd'&&<RndBoard csrf={session.csrf} report={setStatus}/>}
 </>}
 <footer className="ce-footer">Private operational records · No automatic messages, purchases or transfers · <Link to="/app">Back to product</Link></footer>
 </>}
 </main></div></div></StatusContext.Provider>;
}
class ErrorBoundary extends React.Component {
 constructor(props){super(props);this.state={error:false};}
 static getDerivedStateFromError(){return {error:true};}
 componentDidCatch(){this.props.onError('This record could not be displayed. Refresh or export it for review.');}
 render(){return this.state.error?<p>Refresh to reload this record.</p>:this.props.children;}
}
