import React from "react";
import { Link } from "react-router-dom";

export default function ConsumerHome() {
  return <main className="bg-primary text-white min-h-screen">
    <nav className="max-w-5xl mx-auto px-6 py-6 flex items-center justify-between"><Link to="/" className="font-bold text-xl">EDGEBOX</Link><Link to="/business" className="underline text-sm">For your business</Link></nav>
    <section className="max-w-4xl mx-auto px-6 py-20 text-center"><p className="text-blue-300 font-semibold mb-3">EDGEBOX FOR HOME</p><h1 className="text-4xl md:text-6xl font-bold leading-tight">Know what matters. Skip the camera watching.</h1><p className="text-xl text-gray-300 mt-6 max-w-2xl mx-auto">We are exploring a simple home version of Edgebox for people who already have smart cameras.</p><a href="mailto:support@edgebox.africa?subject=Edgebox%20Home%20early%20access&body=I%27m%20interested%20in%20Edgebox%20Home.%20My%20camera%20brand%20is%3A%20" className="inline-block mt-8 px-7 py-4 bg-blue-600 rounded-lg font-semibold">Join the home early-access list</a></section>
    <section className="max-w-4xl mx-auto px-6 py-12"><h2 className="text-3xl font-bold mb-8">What we want it to do</h2><div className="grid md:grid-cols-3 gap-5">{[["Useful alerts","Tell you when something worth checking happens."],["Easy history","Find the event you care about without scrolling through hours of video."],["Works with what you have","Start by supporting popular existing smart-camera setups instead of asking you to replace everything."]].map(([t,d])=><div key={t} className="border border-gray-700 rounded-xl p-6"><h3 className="font-bold text-xl mb-2">{t}</h3><p className="text-gray-300">{d}</p></div>)}</div></section>
    <section className="max-w-4xl mx-auto px-6 py-16 text-center"><h2 className="text-3xl font-bold">Home is not on sale yet.</h2><p className="text-gray-300 mt-4 max-w-xl mx-auto">We will open buying once we know which camera systems to support and can make setup simple. Early-access interest helps us choose what to build first.</p><a href="mailto:support@edgebox.africa?subject=Edgebox%20Home%20early%20access&body=I%27m%20interested%20in%20Edgebox%20Home.%20My%20camera%20brand%20is%3A%20" className="inline-block mt-7 px-7 py-4 bg-blue-600 rounded-lg font-semibold">Tell us your camera brand</a></section>
    <footer className="max-w-4xl mx-auto px-6 py-8 border-t border-gray-800 flex gap-6 text-sm text-gray-400"><Link to="/privacy-policy" className="underline">Privacy</Link><Link to="/terms-of-service" className="underline">Terms</Link><a href="mailto:support@edgebox.africa" className="underline">Contact</a></footer>
  </main>;
}
